### ISSUE TITLE
AADSTS90015: Requested query string is too long

### ISSUE THREAD

**Issue by AndrewR3K** [atinux/nuxt-auth-utils#249]
I am running into an issue where end users are hitting this error `[AADSTS90015: Requested query string is too long](https://devforum.okta.com/t/aadsts90015-requested-query-string-is-too-long/15905)` when redirected to the AD login. 

After digging further into the issue, I noticed that for some odd reason, the "scope" is being appended over 70+* to the authorizationURL.

Has anyone run into this? And if so, do you have a resolution? 

Since this has been extremely hard to consistently reproduce, I have been banging my head against a while all day and have yet to find the root cause. 

Thanks in advance for the help! 

```
https://login.microsoftonline.com/<redacted>/oauth2/v2.0/authorize?client_id=<redacted>&response_type=code&redirect_uri=https:%2F%2Ftesturl.azurestaticapps.net%2Fauth%2Fmicrosoft&scope=Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.Alne_access+Group.Read.All+User.Read+User.ReadBasic.Al+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.ll+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offfline_access+Group.Read.All+User.Read+User.ReadBasifline_access+Group.Read.All+User.Read+User.ReadBasid.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBac.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+emailil+offline_access+Group.Read.All+User.Read+User.Read+offline_access+Group.Read.All+User.Read+User.ReadB.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.Reasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+em+email+offline_access+Group.Read.All+User.Read+User.ail+offline_access+Group.Read.All+User.Read+User.Reroup.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+UseadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openidenid+email+offline_access+Group.Read.All+User.Read+U+email+offline_access+Group.Read.All+User.Read+Userss+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+opee+openid+email+offline_access+Group.Read.All+User.Renid+email+offline_access+Group.Read.All+User.Read+Uaccess+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.ser.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+ofile+openid+email+offline_access+Group.Read.All+Useopenid+email+offline_access+Group.Read.All+User.Reaine_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+Ud+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profil+profile+openid+email+offline_access+Group.Read.Allle+openid+email+offline_access+Group.Read.All+User.offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.ARead+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+prc.All+profile+openid+email+offline_access+Group.Readofile+openid+email+offline_access+Group.Read.All+Usail+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Reer.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.AllBasic.All+profile+openid+email+offline_access+Group.+profile+openid+email+offline_access+Group.Read.Alld+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Grou+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.ReadBasic.All+profile+openid+email+offline_access+GrAll+profile+openid+email+offline_access+Group.Read.penid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasser.ReadBasic.All+profile+openid+email+offline_accesic.All+profile+openid+email+offline_access+Group.Rele+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_accad.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.Readad+User.ReadBasic.All+profile+openid+email+offline_aBasic.All+profile+openid+email+offline_access+Grouprofile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.Rr.Read+User.ReadBasic.All+profile+openid+email+offlieadBasic.All+profile+openid+email+offline_access+Grll+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offoup.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+Use+User.Read+User.ReadBasic.All+profile+openid+email+or.ReadBasic.All+profile+openid+email+offline_accessic.All+profile+openid+email+offline_access+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+Group.Read.All+User.Read+User.ReadBasic.All+profile+openid+email+offline_access+Group.Read.All+User.Read
```

**Comment by AndrewR3K** [comment]
Weirdly it seems the following changes has "resolved" the issue for now, this of course though is not ideal.

I have yet to figure out exactly WHY this is causing sporadic duplicate scopes.

1. Hard coded scope
Example:
```js
// removed:       const scope = config.scope && config.scope.length > 0 ? config.scope : ['User.Read']

return sendRedirect(
        event,
        withQuery(authorizationURL as string, {
          client_id: config.clientId,
          response_type: 'code',
          redirect_uri: redirectURL,
          scope: 'Group.Read.All User.Read User.ReadBasic.All profile openid email offline_access',
        }),
      )
```

2. Removed the spread opp
```js
...config.authorizationParams,
```

**Comment by AndrewR3K** [comment]
Any ideas or updates on this one? Thanks again for this wonderful package.

**Comment by atinux** [comment]
Sorry for the late answer, this is quite weird as the `authorizationParams` should be empty, could you `console.log` it?

**Comment by Degoya-Studio** [comment]
I'm facing the same issue. 400 Bad Request - Request Header too large

**Comment by Jarvis-Level-R** [comment]
This seems to happen because config is reassigned inside the event handler:

  config = defu(config, useRuntimeConfig(event).oauth.oidc, { scope: ['openid'] })

Since config is captured in the closure, it appears to persist between requests, and defu merges arrays instead of replacing them.

Expected behavior:
- config should be resolved fresh per request
- scope should not accumulate across requests

Suggested fix:
- avoid mutating/reassigning the outer config
- use a local per-request object, e.g.

  const resolvedConfig = defu({}, config, useRuntimeConfig(event).oauth.oidc, { scope: ['openid'] })

**Comment by ozfox** [comment]
That's still an issue and tbh I don't know how anybody is defining a non-default scope right now, which seems like a common usecase?! I am using `v0.5.29` and stumbled across this when setting up a Keycloak endpoint.

Everything is fine as long as the `config` parameter and the runtime config don't have a scope defined, because of the fallback/default that's applied later on. As soon as a scope array is configured, eg. `runtimeConfig: { oauth: { keycloak: { scope: ['openid', 'profile'] }}}` the array grows with each request.

I'd contribute a fix, but I don't understand what the original motivation behind `config = defu(config, useRuntimeConfig(event).oauth?.keycloak ... )` was. Resolving the config for every request without mutating the parameter seems to me to be the more stable solution, but I might be missing something.

**Snippet from [src/runtime/server/lib/oauth/keycloak.ts](https://github.com/atinux/nuxt-auth-utils/blob/ceb366b629130a2da539750a86b6cccdcc70ae00/src/runtime/server/lib/oauth/keycloak.ts):** 
```ts
export function defineOAuthKeycloakEventHandler({
  config,
  onSuccess,
  onError,
}: OAuthConfig<OAuthKeycloakConfig>) {
  return eventHandler(async (event: H3Event) => {
    config = defu(config, useRuntimeConfig(event).oauth?.keycloak, {
      authorizationParams: {},
    }) as OAuthKeycloakConfig

    // ...

    if (!query.code) {
      config.scope = config.scope || ['openid']

      // Redirect to Keycloak Oauth page
      return sendRedirect(
        event,
        withQuery(authorizationURL, {
          ...query,
          client_id: config.clientId,
          redirect_uri: redirectURL,
          scope: config.scope.join(' '),
          response_type: 'code',
          ...config.authorizationParams,
        }),
      )
    }

    // ...
}
```

**Workaround: custom handler**

```ts
// server/routes/oauth/keycloak.get.ts
import type { H3Event } from 'h3'
import { eventHandler, getQuery, sendRedirect } from 'h3'
import { withQuery } from 'ufo'
import { defu } from 'defu'
import { handleMissingConfiguration, handleAccessTokenErrorResponse, getOAuthRedirectURL, requestAccessToken } from './node_modules/nuxt-auth-utils/dist/runtime/server/lib/utils';
import { useRuntimeConfig, createError } from '#imports'
import type { OAuthConfig } from '#auth-utils'

export function defineAnotherOAuthKeycloakEventHandler({
  config,
  onSuccess,
  onError,
}: OAuthConfig<OAuthKeycloakConfig>) {
  return eventHandler(async (event: H3Event) => {
    const resolvedConfig = defu(config, useRuntimeConfig(event).oauth?.keycloak, {
      authorizationParams: {},
    }) as OAuthKeycloakConfig

    const query = getQuery<{ code?: string, error?: string }>(event)

    if (query.error) {
      const error = createError({
        statusCode: 401,
        message: `Keycloak login failed: ${query.error || 'Unknown error'}`,
        data: query,
      })
      if (!onError) throw error
      return onError(event, error)
    }

    if (
      !resolvedConfig.clientId
      || !resolvedConfig.clientSecret
      || !resolvedConfig.serverUrl
      || !resolvedConfig.realm
    ) {
      return handleMissingConfiguration(event, 'keycloak', ['clientId', 'clientSecret', 'serverUrl', 'realm'], onError)
    }

    const realmURL = `${resolvedConfig.serverUrl}/realms/${resolvedConfig.realm}`
    const realmURLInternal = `${resolvedConfig.serverUrlInternal || resolvedConfig.serverUrl}/realms/${resolvedConfig.realm}`

    const authorizationURL = `${realmURL}/protocol/openid-connect/auth`
    const tokenURL = `${realmURLInternal}/protocol/openid-connect/token`
    const redirectURL = resolvedConfig.redirectURL || getOAuthRedirectURL(event)

    if (!query.code) {
      resolvedConfig.scope = resolvedConfig.scope || ['openid']

      // Redirect to Keycloak Oauth page
      return sendRedirect(
        event,
        withQuery(authorizationURL, {
          ...query,
          client_id: resolvedConfig.clientId,
          redirect_uri: redirectURL,
          scope: resolvedConfig.scope.join(' '),
          response_type: 'code',
          ...resolvedConfig.authorizationParams,
        }),
      )
    }

    resolvedConfig.scope = resolvedConfig.scope || []
    if (!resolvedConfig.scope.includes('openid')) {
      resolvedConfig.scope.push('openid')
    }

    const tokens = await requestAccessToken(tokenURL, {
      body: {
        grant_type: 'authorization_code',
        client_id: resolvedConfig.clientId,
        client_secret: resolvedConfig.clientSecret,
        redirect_uri: redirectURL,
        code: query.code,
      } })
      .catch((error) => {
        return handleAccessTokenErrorResponse(event, 'keycloak', error?.data || error, onError)
      })

    if (tokens.error) {
      return handleAccessTokenErrorResponse(event, 'keycloak', tokens, onError)
    }

    const accessToken = tokens.access_token

    // TODO: improve typing
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const user: any = await $fetch(
      `${realmURLInternal}/protocol/openid-connect/userinfo`,
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          Accept: 'application/json',
        },
      },
    )

    if (!user) {
      const error = createError({
        statusCode: 500,
        message: 'Could not get Keycloak user',
        data: tokens,
      })
      if (!onError) throw error
      return onError(event, error)
    }

    return onSuccess(event, {
      user,
      tokens,
    })
  })
}
```
